name: semantic-release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'
          cache: 'yarn'

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            shared:
              - 'packages/shared/**'

      - name: install
        run: yarn install

      - name: release
        if: steps.changes.outputs.shared == 'true'
        run: cd packages/shared && yarn install && yarn release
