name: semantic-release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com/vladsovetov/test-monorepo'

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            shared:
              - 'packages/shared/**'

      - name: install
        run: yarn install

      - name: release
        if: steps.changes.outputs.shared == 'true'
        # run: pnpm -r --workspace-concurrency=1 exec -- npx --no-install semantic-release -e semantic-release-monorepo
        run: echo "@vladsovetov:registry=https://npm.pkg.github.com \n //npm.pkg.github.com/:_authToken=${NPM_AUTH_TOKEN}" >> packages/shared/.npmrc && lerna exec --concurrency 1 -- npx --no-install semantic-release -e semantic-release-monorepo
        shell: bash
