name: semantic-release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            shared:
              - 'packages/shared/**'

      - name: release
        if: steps.changes.outputs.shared == 'true'
        run: cd packages/shared && yarn semantic-release -e semantic-release-monorepo
