name: semantic-release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      NPM_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # NPM_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
          registry-url: 'https://npm.pkg.github.com'

      - uses: dorny/paths-filter@v2
        id: changes
        with:
          filters: |
            shared:
              - 'packages/shared/**'

      - name: release
        if: steps.changes.outputs.shared == 'true'
        # run: pnpm -r --workspace-concurrency=1 exec -- npx --no-install semantic-release
        run: cd packages/shared && npx semantic-release
        shell: bash

      - uses: JamieMason/syncpack-github-action@0.2.0
        env:
          # If any options are set to 'fix' then
          # env.GITHUB_TOKEN is needed to push to PRs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
